headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/dmitry/qed-frontend"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.jsx"

[headers.values]
Content-Type = "text/babel; charset=utf-8"
Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=86400"