/* QED build step (run by Netlify) — turns deploy env vars into a static config.

   Env vars (set in Netlify → Site settings → Environment variables):
     BRAND             QED | TDT       (QED = quizeatdrink.com/EN, TDT = tardeodetrivia.com/ES)
     DEV_NOTICE        true | false    (default true — shows the "in development" banner)
     DEFAULT_LANGUAGE  EN | ES         (fallback when BRAND is not set; default EN)

   Output:
     - config.js   regenerated with the resolved values.

   Every page lives at its natural folder path (/corporate/, /celebrations/, …) and
   identifies itself with a baked-in window.QED_SITE, so there is no page-copying step. */

import { writeFileSync } from "node:fs";

const VALID_BRANDS = ["QED", "TDT"];
const brand = VALID_BRANDS.includes((process.env.BRAND || "").toUpperCase())
  ? process.env.BRAND.toUpperCase()
  : null;

// BRAND drives language when set; DEFAULT_LANGUAGE is the local/preview fallback.
const lang = brand === "TDT" ? "ES"
  : brand === "QED" ? "EN"
  : (process.env.DEFAULT_LANGUAGE || "EN").toUpperCase() === "ES" ? "ES" : "EN";

const devNotice = String(process.env.DEV_NOTICE ?? "true").toLowerCase() !== "false";

const config = { defaultLanguage: lang, devNotice, ...(brand && { brand }) };
writeFileSync(
  "config.js",
  `/* generated by build.mjs from Netlify env vars. Edit env vars, not this file. */\n` +
    `window.QED_CONFIG = ${JSON.stringify(config)};\n`
);

console.log("[qed build] config:", config);
