/* QED build step (run by Netlify) — turns deploy env vars into a static config.

   Env vars (set in Netlify → Site settings → Environment variables):
     DEFAULT_LANGUAGE  EN | ES         (default EN)
     DEV_NOTICE        true | false    (default true — shows the "in development" banner)

   Output:
     - config.js   regenerated with the resolved values.

   Every page lives at its natural folder path (/corporate/, /celebrations/, …) and
   identifies itself with a baked-in window.QED_SITE, so there is no page-copying step. */

import { writeFileSync } from "node:fs";

const lang = (process.env.DEFAULT_LANGUAGE || "EN").toUpperCase() === "ES" ? "ES" : "EN";
const devNotice = String(process.env.DEV_NOTICE ?? "true").toLowerCase() !== "false";

const config = { defaultLanguage: lang, devNotice };
writeFileSync(
  "config.js",
  `/* generated by build.mjs from Netlify env vars. Edit env vars, not this file. */\n` +
    `window.QED_CONFIG = ${JSON.stringify(config)};\n`
);

console.log("[qed build] config:", config);
