[build]
  publish = "."
  command = "node build.mjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/babel; charset=utf-8"
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
