/* Bundles scripts/walker.entry.mjs → shared/walker.js (the vendored artifact the pages load).
   Run: `npm run walker:build`. Commit the resulting shared/walker.js.

   We bundle with esbuild (already this repo's toolchain — Netlify bundles the functions with it)
   rather than the walkerOS CLI: the CLI's transitive jsdom dep (html-encoding-sniffer) crashes
   under this repo's Node with a CJS-requires-ESM error, and esbuild gives us a smaller, self-
   contained IIFE with full control. Output is committed (vendored), NOT built on Netlify, so a
   bundling failure can never break the live deploy of either brand.

   REBUILD whenever scripts/walker.entry.mjs (or a walkerOS dep version) changes, then commit
   shared/walker.js. There is no automatic rebuild in the Netlify build. */

import { build } from "esbuild";

await build({
  entryPoints: ["scripts/walker.entry.mjs"],
  outfile: "shared/walker.js",
  bundle: true,
  format: "iife",
  minify: true,
  target: ["es2018"],
  legalComments: "none",
  banner: {
    js: "/* walkerOS bundle — generated by `npm run walker:build` from scripts/walker.entry.mjs. Do not edit by hand. */",
  },
});

console.log("[walker] built shared/walker.js");
